services:
  auth-service:
    image: kerstineboldsen/authservice
    ports:
    - "8201:80"
    depends_on:
    - mongodb
    environment:
      - connectionsstring="mongodb://root:password@localhost:27017/?authSource=admin"
      - database="LoginCredentials"
      - collection="customers"
      - secret="kerrik123456789123456789123456789"
      - issuer="authservice123456789123456789"
  nginx:
    image: nginx:latest
    ports:
    - 4000:4000
    depends_on:
    - auth-service
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf

  mongodb:
    image: mongo:latest
    ports:
    - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
    - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
  images_data:
    external: false